services:
  api:
    build: .
    container_name: my-api-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql+psycopg://app:postgres@db:5432/todos
      BQ_PROJECT_ID: terraform-practice-494215
      GOOGLE_APPLICATION_CREDENTIALS: /gcp/adc.json
    volumes:
      - ./app:/app/app
      - ${HOME}/.config/gcloud/application_default_credentials.json:/gcp/adc.json:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: my-api-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d todos"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: